-- CreateTable
CREATE TABLE "inventory_items" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "location" TEXT NOT NULL,
    "owner" TEXT NOT NULL,
    "description" TEXT,
    "sku" TEXT,
    "category" TEXT,
    "barcode" TEXT,
    "supplier" TEXT,
    "unitOfMeasure" TEXT,
    "weight" TEXT,
    "dimensions" TEXT,
    "dateReceived" TIMESTAMP(3),
    "expirationDate" TIMESTAMP(3),
    "lastUpdated" TIMESTAMP(3),
    "status" TEXT,
    "reorderLevel" INTEGER,
    "reorderQuantity" INTEGER,
    "availability" TEXT,
    "costPrice" DOUBLE PRECISION,
    "sellingPrice" DOUBLE PRECISION,
    "batchNumber" TEXT,
    "serialNumber" TEXT,
    "warehouse" TEXT,
    "condition" TEXT,
    "pickZone" TEXT,
    "returnStatus" TEXT,
    "handlingInstructions" TEXT,

    CONSTRAINT "inventory_items_pkey" PRIMARY KEY ("id")
);
